#!/sbin/openrc-run


start() {

ebegin "Starting afterthedeadlined"
    start-stop-daemon --start --quiet --pidfile /var/run/afterthedeadlined.pid --exec /opt/bin/afterthedeadlined 2>&1  
    eend $? "Failed to start afterthedeadlined"
}

stop() {
	ebegin "Stopping afterthedeadline"
	start-stop-daemon --stop --quiet --pidfile /var/run/afterthedeadlined.pid 
	eend $? "Failed to stop afterthedeadline"
}


